GH-2: Add Streaming Support to SFTP Source
spring-cloud-stream-app-starters/sftp pull request #6
Opened 2017-03-22 18:25 UTC by garyrussell

Resolves #2 

Also, flatten properties to avoid missing descriptions in READMEs.

Requires https://github.com/spring-cloud-stream-app-starters/core/pull/15

2017-03-22 19:30 UTC, artembilan requested changes

2017-03-22 19:30 UTC, artembilan commented on spring-cloud-starter-stream-sink-sftp/src/main/java/org/springframework/cloud/stream/app/sftp/sink/SftpSinkConfiguration.java
> +			sftpSessionFactory.setKnownHosts("#{" + properties.getFactory().getKnownHostsExpression() + "}");
SpEL?
```
/**
 * Specifies the filename that will be used for a host key repository.
 * The file has the same format as OpenSSH's known_hosts file.
 * <p>
 * <b>Required if {@link #setAllowUnknownKeys(boolean) allowUnknownKeys} is
 * false (default).</b>
 * @param knownHosts The known hosts.
 * @see JSch#setKnownHosts(String)
 */
public void setKnownHosts(String knownHosts) {
	this.knownHosts = knownHosts;
}
```

I don't see how it is resolved.
Thanks

2017-03-22 19:43 UTC, garyrussell commented on spring-cloud-starter-stream-sink-sftp/src/main/java/org/springframework/cloud/stream/app/sftp/sink/SftpSinkConfiguration.java
> +			sftpSessionFactory.setKnownHosts("#{" + properties.getFactory().getKnownHostsExpression() + "}");
I didn't look at the code, I just moved it - but you're right - no idea which brain cell generated that, but it must have long ago - it looks like a bad port from XD.

2017-03-22 19:57 UTC, artembilan commented on spring-cloud-starter-stream-sink-sftp/src/main/java/org/springframework/cloud/stream/app/sftp/sink/SftpSinkConfiguration.java
> +			sftpSessionFactory.setKnownHosts("#{" + properties.getFactory().getKnownHostsExpression() + "}");
Well, in XD that looks like:
```
<beans:property name="knownHosts" value="#{${knownHostsExpression:null}}" />
```
Which is really bean initialization SpEL, not a target property value like in this case.
There it has a description like:
```
@ModuleOption("a SpEL expresssion location of known hosts file; required if 'allowUnknownKeys' is false; "
			+ "examples: systemProperties[\"user.home\"]+\"/.ssh/known_hosts\", \"/foo/bar/known_hosts\"")
	public void setKnownHostsExpression(String knownHostsExpression) {
```
Which really makes sense. We can come up with something similar in Java config via `@Value`

2017-03-22 20:55 UTC, artembilan commented on spring-cloud-starter-stream-source-sftp/src/main/java/org/springframework/cloud/stream/app/sftp/source/SftpSourceConfiguration.java
> +		BeanUtils.copyProperties(this.defaultPoller, poller, "transactionSynchronizationFactory");
???
Why do we need to copy that default one?
We are in the microservice here, so we have only singe `PollerMetadata` and just for this single channel adapter in the whole application. Therefore I think it is still safe just to enhance an existing `defaultPoller` without further `Consumer<SourcePollingChannelAdapterSpec>` creation. We still can rely on the `PollerMetadata.getDefaultPollerMetadata(this.beanFactory)` in the target `SourcePollingChannelAdapterFactoryBean`.

2017-03-22 21:02 UTC, garyrussell commented on spring-cloud-starter-stream-source-sftp/src/main/java/org/springframework/cloud/stream/app/sftp/source/SftpSourceConfiguration.java
> +		BeanUtils.copyProperties(this.defaultPoller, poller, "transactionSynchronizationFactory");
I don't think we can make that assumption people might `@Import` this configuration.

2017-03-22 21:03 UTC, garyrussell commented
I need to rebase and polish this after merging your other PR.

2017-03-22 21:22 UTC, garyrussell commented
Rebased; fixed conflicts; added doc polish.

2017-03-22 23:56 UTC, artembilan approved these changes
LGTM
Merging...

2017-03-23 00:02 UTC, artembilan commented
Merged as https://github.com/spring-cloud-stream-app-starters/sftp/commit/9642029e5e36e0f4799689433399b24d5ef0c91d

2017-03-23 00:02 UTC, closed without merging